name:                adventofcode
version:             0.1.0.0
github:              "nicolashery/adventofcode"
license:             BSD3
author:              "Nicolas Hery"
maintainer:          "hi@nicolashery.com"
copyright:           "2018 Nicolas Hery"

ghc-options: -Wall

default-extensions:
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - containers
  - matrix
  - parsec
  - text

library:
  source-dirs: src

executables:
  adventofcode:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adventofcode

tests:
  adventofcode-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adventofcode
      - hspec
